var test = 'merlin'

// d8 --print-ast ./src/test.js

// [generating bytecode for function: ]
// --- AST ---
// FUNC at 0
// . KIND 0
// . LITERAL ID 0
// . SUSPEND COUNT 0
// . NAME ""
// . INFERRED NAME ""
// . DECLS
// . . VARIABLE (0x7fadec01be50) (mode = VAR, assigned = true) "test"
// . BLOCK NOCOMPLETIONS at -1
// . . EXPRESSION STATEMENT at 11
// . . . INIT at 11
// . . . . VAR PROXY unallocated (0x7fadec01be50) (mode = VAR, assigned = true) "test"
// . . . . LITERAL "merlin"

// d8 --print-scopes ./src/test.js

// Global scope:
// global { // (0x7fcff6825230) (0, 494)
//   // will be compiled
//   // NormalFunction
//   // 1 stack slots
//   // temporary vars:
//   TEMPORARY .result;  // (0x7fcff6825540) local[0]
//   // local vars:
//   VAR test;  // (0x7fcff6825450)
// }

// d8 --print-bytecode test.js

// [generated bytecode for function:  (0x1a270025376d <SharedFunctionInfo>)]
// Bytecode length: 18
// Parameter count 1
// Register count 3
// Frame size 24
// Bytecode age: 0
//          0x1a27002537f6 @    0 : 13 00             LdaConstant [0]
//          0x1a27002537f8 @    2 : c3                Star1
//          0x1a27002537f9 @    3 : 19 fe f8          Mov <closure>, r2
//          0x1a27002537fc @    6 : 65 58 01 f9 02    CallRuntime [DeclareGlobals], r1-r2
//          0x1a2700253801 @   11 : 13 01             LdaConstant [1]
//          0x1a2700253803 @   13 : 23 02 00          StaGlobal [2], [0]
//          0x1a2700253806 @   16 : 0e                LdaUndefined
//          0x1a2700253807 @   17 : a9                Return
// Constant pool (size = 3)
// 0x1a27002537c1: [FixedArray] in OldSpace
//  - map: 0x1a2700002239 <Map>
//  - length: 3
//            0: 0x1a27002537b5 <FixedArray[1]>
//            1: 0x1a270025374d <String[6]: #merlin>
//            2: 0x1a27001c2d1d <String[4]: #test>
// Handler Table (size = 0)
// Source Position Table (size = 0)
